version: "2.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    depends_on:
      - es01
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
      enterpriseSearch.host: http://host.docker.iternal:3002
    ports:
      - 5601:5601
    networks:
      - esnet


  enterprise01:
    image: docker.elastic.co/enterprise-search/enterprise-search:7.10.2
    container_name: enterprise01
    environment:
      elasticsearch.host: http://host.docker.internal:9200
      elasticsearch.username: elastic
      elasticsearch.password: changeme
      allow_es_settings_modification: 'true'
      secret_management.encryption_keys: '[4a2cd3f81d39bf28738c10db0ca782095ffac07279561809eecc722e0c20eb09]'
    volumes:
      - enterprise01:/usr/share/enterprise-search/data
    ports:
      - 3002:3002
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  enterprise01:
    driver: local

networks:
  esnet:
    name: esnet
